version: "3"
services:
  frontend:
    build: "./front_cloud"
    volumes:
      - /home/app_back/images_users:/home/app_front/public/images_users
    ports:
      - "3000:3000"

  db:
    image: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: backcloud
    networks:
      - db-network

  backend:
    build: "./back_cloud"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    networks:
      - db-network

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery_worker:
    container_name: celery_worker
    build: "./back_cloud"
    command: celery -A celery_worker worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend
volumes:
  postgres_data:

networks:
  db-network: