version: "3"
services:
  db:
    image: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: backcloud
  backend:
    build: "./back_cloud"
    ports:
      - "8000:8000"
    links:
      - db

  frontend:
    build: "./front_cloud"
    volumes:
      - /home/app_back/images_users:/home/app_front/public/images_users
    ports:
      - "3000:3000"
volumes:
  postgres_data: